name: Build Skedl.Api

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_skedl_api:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        run: |
          cd Skedl.Api
          dotnet restore
          dotnet publish -c Release -o ./publish
